GITHUB_TOKEN = "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" 
GITHUB_USERNAME = "sumansourabhcsc" 
GITHUB_REPO = "portfolio" 
GITHUB_FILE_PATH = "mutualfund_app/data/mutualfund/daily_summary.csv"
ADMIN_PASSWORD = "7654uytr"
LOGIN_PASSWORD = "who@mI321"
